<?php
file_put_contents('app/Models/UnitKerja.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass UnitKerja extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'unit_kerjas';\n    protected \$fillable = ['nama_unit'];\n\n    public function tenagaKependidikans()\n    {\n        return \$this->hasMany(TenagaKependidikan::class);\n    }\n}\n");

file_put_contents('app/Models/LokasiKantor.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass LokasiKantor extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'lokasi_kantors';\n    protected \$fillable = ['nama_lokasi', 'latitude', 'longitude', 'radius'];\n}\n");

file_put_contents('app/Models/JadwalKerja.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass JadwalKerja extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'jadwal_kerjas';\n    protected \$fillable = ['jam_masuk', 'jam_pulang'];\n}\n");

file_put_contents('app/Models/TenagaKependidikan.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass TenagaKependidikan extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'tenaga_kependidikans';\n    protected \$fillable = ['user_id', 'nip', 'nama', 'unit_kerja_id'];\n\n    public function user()\n    {\n        return \$this->belongsTo(User::class);\n    }\n\n    public function unitKerja()\n    {\n        return \$this->belongsTo(UnitKerja::class);\n    }\n}\n");

file_put_contents('app/Models/Presensi.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass Presensi extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'presensis';\n    protected \$fillable = ['user_id', 'tanggal', 'jam_masuk', 'jam_pulang', 'lat', 'lng'];\n\n    public function user()\n    {\n        return \$this->belongsTo(User::class);\n    }\n\n    public function foto()\n    {\n        return \$this->hasMany(PresensiFoto::class);\n    }\n\n    public function log()\n    {\n        return \$this->hasMany(PresensiLog::class);\n    }\n}\n");

file_put_contents('app/Models/PresensiFoto.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass PresensiFoto extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'presensi_fotos';\n    protected \$fillable = ['presensi_id', 'foto'];\n\n    public function presensi()\n    {\n        return \$this->belongsTo(Presensi::class);\n    }\n}\n");

file_put_contents('app/Models/PresensiLog.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass PresensiLog extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'presensi_logs';\n    protected \$fillable = ['presensi_id', 'keterangan'];\n\n    public function presensi()\n    {\n        return \$this->belongsTo(Presensi::class);\n    }\n}\n");

file_put_contents('app/Models/RekapPresensi.php', "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\n\nclass RekapPresensi extends Model\n{\n    use HasFactory;\n\n    protected \$table = 'rekap_presensis';\n    protected \$fillable = ['user_id', 'bulan', 'tahun', 'hadir', 'alfa'];\n\n    public function user()\n    {\n        return \$this->belongsTo(User::class);\n    }\n}\n");

file_put_contents('database/migrations/2026_04_05_142642_create_unit_kerjas_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('unit_kerjas', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('nama_unit');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('unit_kerjas');\n    }\n};\n");

file_put_contents('database/migrations/2026_04_05_142641_create_lokasi_kantors_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('lokasi_kantors', function (Blueprint \$table) {\n            \$table->id();\n            \$table->string('nama_lokasi');\n            \$table->string('latitude');\n            \$table->string('longitude');\n            \$table->integer('radius');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('lokasi_kantors');\n    }\n};\n");

file_put_contents('database/migrations/2026_04_05_142641_create_jadwal_kerjas_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('jadwal_kerjas', function (Blueprint \$table) {\n            \$table->id();\n            \$table->time('jam_masuk');\n            \$table->time('jam_pulang');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('jadwal_kerjas');\n    }\n};\n");

file_put_contents('database/migrations/2026_04_05_142645_create_tenaga_kependidikans_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('tenaga_kependidikans', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('user_id')->constrained('users')->onDelete('cascade');\n            \$table->string('nip')->unique();\n            \$table->string('nama');\n            \$table->foreignId('unit_kerja_id')->constrained('unit_kerjas')->onDelete('cascade');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('tenaga_kependidikans');\n    }\n};\n");

file_put_contents('database/migrations/2026_04_05_142643_create_presensis_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('presensis', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('user_id')->constrained('users')->onDelete('cascade');\n            \$table->date('tanggal');\n            \$table->time('jam_masuk')->nullable();\n            \$table->time('jam_pulang')->nullable();\n            \$table->string('lat')->nullable();\n            \$table->string('lng')->nullable();\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('presensis');\n    }\n};\n");

file_put_contents('database/migrations/2026_04_05_142646_create_presensi_fotos_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('presensi_fotos', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('presensi_id')->constrained('presensis')->onDelete('cascade');\n            \$table->string('foto');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('presensi_fotos');\n    }\n};\n");

file_put_contents('database/migrations/2026_04_05_142644_create_presensi_logs_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('presensi_logs', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('presensi_id')->constrained('presensis')->onDelete('cascade');\n            \$table->text('keterangan');\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('presensi_logs');\n    }\n};\n");

file_put_contents('database/migrations/2026_04_05_142644_create_rekap_presensis_table.php', "<?php\n\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\n\nreturn new class extends Migration\n{\n    public function up(): void\n    {\n        Schema::create('rekap_presensis', function (Blueprint \$table) {\n            \$table->id();\n            \$table->foreignId('user_id')->constrained('users')->onDelete('cascade');\n            \$table->integer('bulan');\n            \$table->integer('tahun');\n            \$table->integer('hadir')->default(0);\n            \$table->integer('alfa')->default(0);\n            \$table->timestamps();\n        });\n    }\n\n    public function down(): void\n    {\n        Schema::dropIfExists('rekap_presensis');\n    }\n};\n");

echo "Done.\n";
